language: haskell

ghc:
  - 8.4

sudo: false

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/8.4.3/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.4.3

script:
  - stack --no-terminal --skip-ghc-check test

cache:
  directories:
    - $HOME/.stack
